- name: Deploy PHP App using Docker
  hosts: test
  become: yes
  vars:
    app_name: phpapp
    app_repo: https://github.com/aryanxcodex/projCert-DevOps
    app_dir: /home/ubuntu/phpapp
    dockerfile_dir: "{{ app_dir }}"
    app_image: "phpapp:{{ ansible_date_time.iso8601 }}"  # Unique tag
    app_port: 80

  tasks:
    - name: Remove old container
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent
        force_kill: yes

    - name: Delete old code
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone repo
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        force: yes

    - name: Check Dockerfile exists
      ansible.builtin.stat:
        path: "{{ dockerfile_dir }}/Dockerfile"
      register: dockerfile_stat

    - name: Fail if no Dockerfile
      ansible.builtin.fail:
        msg: "Dockerfile missing in {{ dockerfile_dir }}"
      when: not dockerfile_stat.stat.exists

    - name: Remove old image
      community.docker.docker_image:
        name: "{{ app_image }}"
        state: absent
      ignore_errors: yes

    - name: Build new image
      community.docker.docker_image:
        name: "{{ app_image }}"
        source: build
        build:
          path: "{{ dockerfile_dir }}"
          nocache: yes
        state: present

    - name: Run container
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        ports:
          - "{{ app_port }}:80"
        restart_policy: always