- name: Deploy PHP App using Docker
  hosts: test
  become: yes
  vars:
    app_name: phpapp
    app_repo: https://github.com/aryanxcodex/projCert-DevOps
    app_dir: /home/ubuntu/phpapp
    dockerfile_dir: /home/ubuntu/phpapp  # Dockerfile is at the root of the repo
    app_image: phpapp
    app_port: 80

  tasks:
    - name: Ensure old container is removed (if running)
      docker_container:
        name: "{{ app_name }}"
        state: absent
        force_kill: yes

    - name: Ensure old code is removed
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone latest code from GitHub
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        force: yes

    - name: Build Docker image from cloned code
      docker_image:
        name: "{{ app_image }}"
        path: "{{ dockerfile_dir }}"
        state: present

    - name: Run Docker container from built image
      docker_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        ports:
          - "{{ app_port }}:80"
        restart_policy: always
