- name: Install Docker
  hosts: test
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker APT repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: latest

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
